language: python
python: 
  - "2.7"
branches:
  only:
    - master
services:
  - couchdb
before_script:
  - pip install coverage coveralls
script:
  - coverage run --source=cloudant setup.py test
after_success:
  - coveralls